spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pma-springbootdb
    username: postgres
    password: adm!nd42
    initialization-mode: never
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

    properties:
      javax:
        persistence:
          validation:
            mode: none
  thymeleaf:
    cache: false
  mvc:
    dispatch-options-request: true


version: 3.0.0
#spring:
#  h2:
#    console:
#      enabled: true
#  jpa:
#    show-sql: true
#    open-in-view: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQL92Dialect
#  thymeleaf:
#    cache: false
#logging:
#  level:
#    com.romz.pma : debug
