spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pma-springbootdb
    username: postgres
    password: adm!nd42
    initialization-mode: never
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
#    properties:
#      hibernate:
#        jdbc:
#          lob:
#            non_contextual_creation: true
  thymeleaf:
    cache: false
version: 3.0.0
